import json
from pathlib import Path
from typing import Any


class RawResultReaderError(Exception):
    """Raised when a raw collector result cannot be read."""


class RawResultReader:
    """
    Reads raw JSON files generated by the Result Collector.
    """

    def __init__(
        self,
        output_directory: str = "output",
    ) -> None:
        self.output_directory = Path(output_directory)

    def find_component_files(
        self,
        execution_id: str,
        entity_name: str,
        component_name: str | None = None,
    ) -> list[Path]:
        """
        Find raw JSON files for an execution.

        All components:
            output/<execution-id>/raw/<entity>/*/*.json

        One component:
            output/<execution-id>/raw/<entity>/<component>/*.json
        """

        raw_directory = (
            self.output_directory
            / execution_id
            / "raw"
            / entity_name
        )

        if not raw_directory.exists():
            raise RawResultReaderError(
                f"Raw result directory does not exist: "
                f"{raw_directory.resolve()}"
            )

        if component_name:
            component_directory = (
                raw_directory / component_name
            )

            files = sorted(
                file_path
                for file_path in component_directory.glob(
                    "*.json"
                )
                if file_path.is_file()
            )

        else:
            files = sorted(
                file_path
                for file_path in raw_directory.glob(
                    "*/*.json"
                )
                if file_path.is_file()
            )

        if not files:
            raise RawResultReaderError(
                f"No raw JSON files found under: "
                f"{raw_directory.resolve()}"
            )

        return files

    @staticmethod
    def read(
        file_path: Path,
    ) -> dict[str, Any]:
        """
        Read and validate one raw JSON file.
        """

        if not file_path.exists():
            raise RawResultReaderError(
                f"Raw result file does not exist: {file_path}"
            )

        try:
            with file_path.open(
                "r",
                encoding="utf-8",
            ) as file:
                content = json.load(file)

        except json.JSONDecodeError as exc:
            raise RawResultReaderError(
                f"Invalid JSON in file: {file_path}"
            ) from exc

        except OSError as exc:
            raise RawResultReaderError(
                f"Could not read '{file_path}': {exc}"
            ) from exc

        if not isinstance(content, dict):
            raise RawResultReaderError(
                f"Expected a JSON object in: {file_path}"
            )

        return content